import { useState, useCallback } from 'react';
import { useLocalStorage } from './useLocalStorage';
import { STORAGE_KEYS } from '../constants';
import { processFile } from '../utils/fileProcessors';

/**
 * Custom hook for managing the knowledge base (uploaded files and their content)
 * This is the foundation for your personal AI's long-term memory
 */
export function useKnowledgeBase() {
  const [knowledgeBase, setKnowledgeBase] = useLocalStorage(STORAGE_KEYS.KNOWLEDGE_BASE, []);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStatus, setProcessingStatus] = useState('');

  /**
   * Add a file to the knowledge base
   */
  const addFile = useCallback(async (file) => {
    setIsProcessing(true);
    setProcessingStatus(`Processing ${file.name}...`);

    try {
      // Process the file to extract text content
      const processed = await processFile(file);

      // Create knowledge base entry
      const entry = {
        id: Date.now() + Math.random(), // Unique ID
        fileName: file.name,
        fileType: file.type,
        fileSize: file.size,
        content: processed.content,
        imageData: processed.imageData, // For images
        metadata: processed.metadata,
        addedAt: new Date().toISOString(),
        tags: [], // User can add tags later
        summary: '', // Can be generated by AI later
        lastUsed: null,
      };

      // Add to knowledge base
      setKnowledgeBase(prev => [...prev, entry]);

      setProcessingStatus('');
      setIsProcessing(false);

      return entry;
    } catch (error) {
      setProcessingStatus('');
      setIsProcessing(false);
      throw error;
    }
  }, [setKnowledgeBase]);

  /**
   * Add multiple files to the knowledge base
   */
  const addFiles = useCallback(async (files) => {
    const results = [];
    const errors = [];

    for (let i = 0; i < files.length; i++) {
      try {
        const entry = await addFile(files[i]);
        results.push(entry);
      } catch (error) {
        errors.push({ file: files[i].name, error: error.message });
      }
    }

    return { results, errors };
  }, [addFile]);

  /**
   * Remove a file from the knowledge base
   */
  const removeFile = useCallback((fileId) => {
    setKnowledgeBase(prev => prev.filter(entry => entry.id !== fileId));
  }, [setKnowledgeBase]);

  /**
   * Update file metadata (tags, summary, etc.)
   */
  const updateFile = useCallback((fileId, updates) => {
    setKnowledgeBase(prev =>
      prev.map(entry =>
        entry.id === fileId ? { ...entry, ...updates } : entry
      )
    );
  }, [setKnowledgeBase]);

  /**
   * Search knowledge base by filename or content
   */
  const searchKnowledgeBase = useCallback((query) => {
    if (!query) return knowledgeBase;

    const lowerQuery = query.toLowerCase();
    return knowledgeBase.filter(entry =>
      entry.fileName.toLowerCase().includes(lowerQuery) ||
      entry.content.toLowerCase().includes(lowerQuery) ||
      entry.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  }, [knowledgeBase]);

  /**
   * Get all files with a specific tag
   */
  const getFilesByTag = useCallback((tag) => {
    return knowledgeBase.filter(entry =>
      entry.tags.includes(tag)
    );
  }, [knowledgeBase]);

  /**
   * Get context from knowledge base for chat
   * This creates a summary of relevant files to include in the conversation
   */
  const getKnowledgeContext = useCallback((limit = 5) => {
    if (knowledgeBase.length === 0) return '';

    // Sort by most recently added/used
    const sorted = [...knowledgeBase].sort((a, b) => {
      const dateA = new Date(a.lastUsed || a.addedAt);
      const dateB = new Date(b.lastUsed || b.addedAt);
      return dateB - dateA;
    });

    // Take the most recent files up to limit
    const recentFiles = sorted.slice(0, limit);

    // Build context string
    let context = 'Available knowledge base files:\n\n';
    recentFiles.forEach(file => {
      context += `File: ${file.fileName}\n`;
      if (file.summary) {
        context += `Summary: ${file.summary}\n`;
      } else {
        // Use first 200 characters as preview
        const preview = file.content.slice(0, 200).trim();
        context += `Preview: ${preview}${file.content.length > 200 ? '...' : ''}\n`;
      }
      context += '\n';
    });

    return context;
  }, [knowledgeBase]);

  /**
   * Get specific file content
   */
  const getFileContent = useCallback((fileId) => {
    const file = knowledgeBase.find(entry => entry.id === fileId);
    return file ? file.content : null;
  }, [knowledgeBase]);

  /**
   * Mark file as used (for relevance sorting)
   */
  const markFileAsUsed = useCallback((fileId) => {
    updateFile(fileId, { lastUsed: new Date().toISOString() });
  }, [updateFile]);

  /**
   * Generate summary for a file using the AI
   */
  const generateSummary = useCallback(async (fileId, generateFn) => {
    const file = knowledgeBase.find(entry => entry.id === fileId);
    if (!file) return;

    try {
      const summary = await generateFn(file.content);
      updateFile(fileId, { summary });
      return summary;
    } catch (error) {
      console.error('Failed to generate summary:', error);
      throw error;
    }
  }, [knowledgeBase, updateFile]);

  /**
   * Clear all knowledge base (with confirmation in UI)
   */
  const clearKnowledgeBase = useCallback(() => {
    setKnowledgeBase([]);
  }, [setKnowledgeBase]);

  /**
   * Get knowledge base statistics
   */
  const getStats = useCallback(() => {
    return {
      totalFiles: knowledgeBase.length,
      totalSize: knowledgeBase.reduce((sum, file) => sum + file.fileSize, 0),
      fileTypes: [...new Set(knowledgeBase.map(f => f.fileType))],
      tags: [...new Set(knowledgeBase.flatMap(f => f.tags))],
    };
  }, [knowledgeBase]);

  return {
    knowledgeBase,
    isProcessing,
    processingStatus,
    addFile,
    addFiles,
    removeFile,
    updateFile,
    searchKnowledgeBase,
    getFilesByTag,
    getKnowledgeContext,
    getFileContent,
    markFileAsUsed,
    generateSummary,
    clearKnowledgeBase,
    getStats,
  };
}
